export const SAVE_FUEL_SAVINGS      = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const REQUEST_CODE         = 'REQUEST_CODE';
export const REQUEST_ACCESS_TOKEN = 'REQUEST_ACCESS_TOKEN';
export const REQUEST_JWT_TOKEN    = 'REQUEST_JWT_TOKEN';
export const SAVE_JWT_TOKEN       = 'SAVE_JWT_TOKEN';
